### ISSUE TITLE
Can't make the medge. medge在git后make失败

### ISSUE THREAD

**Issue by werner-balonius** [Water-Melon/Medge#1]
已安装好melang和melon环境：Melang 0.6.0. 
输入make命令后：test -d objs || mkdir objs
test -d bin || mkdir bin

输入make install命令后：test -d ~/Desktop/桌面/environment/Medge || mkdir -p ~/Desktop/桌面/environment/Medge
cp -fr bin/medge ~/Desktop/桌面/environment/Medge/

在完成上述两个命令后，输入medge -h 
输出：zsh: command not found: medge

**Comment by Water-Melon** [comment]
抱歉，才看到你的问题。
Windows下直接输入命令会提示这个，你需要设置一下环境变量`PATH`，在里面追加一下medge的安装目录。
UNIX环境下一般都会放到`/usr/bin`下，所以可以直接输入命令即可。

另外，现在medge支持了Docker，你可以`docker pull melonc/medge`拉取medge的image来使用。
